[main]
site_name       = "dupe.sh"
site_url        = "https://www.dupe.sh"
description     = "jaunts through the software frontiers"

[generator]
input_dir       = "src/content"
static_dir      = "src/static"
output_dir      = "build"
deploy_dir      = "deploy"

[templates]
dir             = "src/templates"
default         = "page.htmlua"
index_page      = "index.htmlua"
post            = "post.htmlua"
feed            = "feed.xmlua"
