[main]
site_name       = "Ultima"
site_url        = "https://www.dupe.sh"

[generator]
input_dir       = "src/content"
static_dir      = "src/static"
output_dir      = "build"
deploy_dir      = "deploy"

[templates]
dir             = "src/templates"
default         = "page.lhtml"
index_page      = "index.lhtml"
post            = "post.lhtml"
