[main]
site_name       = "Ultima"

[generator]
input_dir       = "src/content"
static_dir      = "src/static"
output_dir      = "build"

[templates]
dir             = "src/templates"
default         = "page.lhtml"
index_page      = "index.lhtml"
post            = "post.lhtml"
